
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 22 23:37:01 CDT 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 25;
  public static final int Parentesis_c = 19;
  public static final int Parentesis_a = 18;
  public static final int Char = 4;
  public static final int Suma = 6;
  public static final int Numero = 27;
  public static final int OpOr = 11;
  public static final int Identificador = 2;
  public static final int Comillas = 17;
  public static final int Int = 3;
  public static final int Llave_c = 21;
  public static final int Llave_a = 20;
  public static final int Coma = 13;
  public static final int Op_relacional = 10;
  public static final int P_coma = 16;
  public static final int T_dato = 5;
  public static final int Main = 26;
  public static final int EOF = 0;
  public static final int Division = 9;
  public static final int If = 22;
  public static final int Resta = 8;
  public static final int Return = 24;
  public static final int OpAnd = 12;
  public static final int error = 1;
  public static final int Igual = 15;
  public static final int While = 23;
  public static final int Multiplicacion = 7;
  public static final int OpNot = 14;
}

